version: 0.2.0.{build}

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration:
  - Release
  
before_build:
# This is necessary for any project that depends on a NuGet package that inject MSBuild targets (like SharpDx).
# NuGet restore is run during the call to MSBuild, and fails to inject SharpDx.targets, causing the build to fail.
# Running package restore before the build resolves this issue.
  - cmd: cd "Gold Rush"
  - cmd: nuget restore
  - cmd: cd ..

#branches:
#  only: feature-appveyor
#  configuration: Release

environment:
    StagingServer: 
      secure: qhbRgh95uxWbExYwTy/kljHkNPXXNnCRipxSaTxQ++E=
    StagingUser: 
      secure: UsFvnkJmjGGxRqYxW0bemqgK+Izvr1mj29L8JMSjGUI=
    StagingPass:
      secure: gAuX93BArgXIeBCv2SCvDLbeEs+PmaBFqSkDBxFQ07o=

branches:
  only:
    - feature-appveyor
  configuration: Release

  
deploy_script: if $(APPVEYOR_REPO_BRANCH)==feature-appveyor ncftpput -R -v -u "$(StagingUser)" -p "$(StagingPass)" $(StagingServer) / "/Gold Rush/Gold Rush"