version: 0.2.0.{build}

install:
  - cinst ncftp

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration:
  - Release
  
before_build:
# This is necessary for any project that depends on a NuGet package that inject MSBuild targets (like SharpDx).
# NuGet restore is run during the call to MSBuild, and fails to inject SharpDx.targets, causing the build to fail.
# Running package restore before the build resolves this issue.
  - cmd: cd "Gold Rush"
  - cmd: nuget restore
  - cmd: cd ..
  #- cmd: sourceanalyzer -clean

#branches:
#  only: feature-appveyor
#  configuration: Release

environment:
    StagingServer: 
      secure: qhbRgh95uxWbExYwTy/kljHkNPXXNnCRipxSaTxQ++E=
    StagingUser: 
      secure: UsFvnkJmjGGxRqYxW0bemqgK+Izvr1mj29L8JMSjGUI=
    StagingPass:
      secure: HqPvEYuYGf9g31Rt+GMQ6Q==

artifacts:
  - path: "Gold Rush"
    name: ProjectFolder

deploy:
  - provider: FTP
    artifact: ProjectFolder
    server: 
      secure: qhbRgh95uxWbExYwTy/kljHkNPXXNnCRipxSaTxQ++E=
    username: 
      secure: UsFvnkJmjGGxRqYxW0bemqgK+Izvr1mj29L8JMSjGUI=
    password:
      secure: HqPvEYuYGf9g31Rt+GMQ6Q==
    #folder: does default to recommended dir?
    enable_sll: true
    #application: # app artifact
    on:
      configuration: Release
      branch: staging
    

#branches:
#  only:
#    - feature-appveyor
#  configuration: Release
  
#deploy_script: cd "Gold Rush\Gold Rush" & if "%APPVEYOR_REPO_BRANCH%"=="feature-appveyor" ncftpput -R -v -u "%StagingUser%" -p "%StagingPass%" %StagingServer% "" ""